"""The README's factual half — the paths it draws, the commands it prints, the tools it lists.

None of this is architecture; all of it is what a newcomer types in the first hour. It is also the
part that rots fastest and most invisibly, because it is the part nobody re-reads: a renamed
directory, a target dropped from the Makefile, a linter removed from the dev group all leave the
README saying something that was true once.

The two tables are held by an explicit map from the README's own row labels to the string that
proves the row. Asserting the labels *are* the map's keys is what makes a new row a decision:
adding a tool to the table without saying where it lives fails here.
"""

import re
from pathlib import Path

from tests.meta.readme import diagram_containing, normalised, text

_ROOT = Path(__file__).resolve().parents[2]

# Where each stack row's choice can be found. The Choice column is prose ("SQLAlchemy 2.x
# (async)"), so the row is proved by the token a machine can look up rather than by the cell.
_STACK = {
    "**Web framework**": "fastapi",
    "**HTML rendering**": "jinja2",
    "**Styling**": "daisyui",
    "**ORM**": "sqlalchemy",
    "**Auth + Storage**": "supabase",
    "**Database**": "supabase",
    "**Migrations**": "supabase",
    "**ASGI server**": "hypercorn",
    "**Dependency management**": "uv.lock",
    "**Python**": "3.14",
}

# Same shape for the quality tools. Several are not Python packages — Biome and gherkin-lint ride
# npm, droast is a GitHub Action — so what is checked is that the repo still configures them
# somewhere, which is the claim the table actually makes.
_TOOLS = {
    "**ruff**": "ruff",
    "**Biome**": "biome",
    "**djlint**": "djlint",
    "**sqlfluff**": "sqlfluff",
    "**gherkin-lint**": "gherkin-lint",
    "**yamllint**": "yamllint",
    "**validate-pyproject**": "validate-pyproject",
    "**zizmor**": "zizmor",
    "**droast**": "droast",
    "**ty**": "ty",
    "**pyright**": "pyright",
    "**import-linter**": "import-linter",
    "**pip-audit**": "pip-audit",
    "**pre-commit**": "pre-commit",
    "**pytest + pytest-asyncio**": "pytest-asyncio",
    "**pytest-bdd + Playwright**": "pytest-bdd",
    "**coverage**": "coverage",
}

# Read as one blob: a tool proves itself by being configured anywhere the build looks.
_CONFIGURED_IN = (
    "pyproject.toml",
    "package.json",
    "Makefile",
    "uv.lock",
    ".pre-commit-config.yaml",
)

# Drawn in the structure tree and produced by the build rather than committed: `static/` is
# gitignored (`make install` rebuilds it) and `client/` is regenerated by `make client-gen`.
_GENERATED = {"static", "client"}


def _table_rows(header: str) -> dict[str, str]:
    """The README table starting at ``header``, as ``{first cell: second cell}``."""
    block = text()[text().index(header) :]
    rows = block[: block.index("\n\n")].splitlines()[2:]
    cells = [[cell.strip() for cell in row.strip().strip("|").split("|")] for row in rows]
    return {row[0]: row[1] for row in cells}


def _configuration() -> str:
    return "\n".join(
        (_ROOT / name).read_text() for name in _CONFIGURED_IN if (_ROOT / name).exists()
    ).lower()


def _tree_paths() -> list[str]:
    """Every path the structure tree draws, resolved against the repo root."""
    stack: list[str] = []
    paths = []
    for row in diagram_containing("labase.py/").splitlines():
        drawn_line = row.split("#")[0].rstrip()
        if not drawn_line.strip():
            continue
        drawn = re.match(r"^([│\s├└─]*?)([\w./*-]+/?)$", drawn_line)
        assert drawn is not None, f"the structure tree drew a line nothing can read: {row!r}"
        prefix, name = drawn.groups()
        stack = [*stack[: len(prefix) // 4], name.rstrip("/")]
        if stack[0] == "labase.py" and len(stack) > 1:
            paths.append("/".join(stack[1:]))
    return paths


def test_every_path_the_structure_tree_draws_exists():
    """A tree is the first thing read and the last thing updated."""
    missing = {
        path
        for path in _tree_paths()
        if path.split("/")[0] not in _GENERATED
        and not (
            list((_ROOT / path).parent.glob(Path(path).name))
            if "*" in path
            else (_ROOT / path).exists()
        )
    }

    assert missing == set()


def test_every_documented_command_exists():
    """The README prints twelve `make` targets. A target renamed in the Makefile leaves the README
    telling a newcomer to run something that answers "No rule to make target"."""
    documented = set(re.findall(r"^make ([a-z][\w-]*)", text(), re.MULTILINE))
    declared = set(re.findall(r"^([a-z][\w-]*):", (_ROOT / "Makefile").read_text(), re.MULTILINE))

    assert documented - declared == set()


def test_the_stack_table_names_what_is_installed():
    """Ten rows, each proved by a token the build files still contain."""
    configuration = _configuration()
    rows = _table_rows("| Layer")

    assert (
        set(rows),
        {label for label, token in _STACK.items() if token not in configuration},
    ) == (
        set(_STACK),
        set(),
    )


def test_every_quality_tool_in_the_table_is_still_configured():
    """Eighteen tools advertised as the gate. One removed and left in the table is a promise the
    repo stopped keeping — and the table is what a reader trusts instead of running `make lint`."""
    configuration = _configuration()
    rows = _table_rows("| Tool")

    assert (
        set(rows),
        {label for label, token in _TOOLS.items() if token not in configuration},
    ) == (
        set(_TOOLS),
        set(),
    )


def test_the_test_environment_file_is_committed_and_local():
    """`.env.test` is the one env file the README says is in the repo, because `make test` reads it
    and points it at localhost — a `.env.test` that drifted to the docker host silently runs the
    suite against the wrong stack."""
    env_test = _ROOT / ".env.test"
    ignored = ".env.test" in (_ROOT / ".gitignore").read_text()

    assert (env_test.exists(), ignored, "host.docker.internal" in env_test.read_text()) == (
        True,
        False,
        False,
    )


def test_every_readme_pointer_names_something_the_readme_says():
    """`(README: the log sink)` in a module docstring is a promise that the README carries the rule
    this file only applies. The pointer is prose, so a reworded heading leaves it pointing at
    nothing and the module quietly becomes the only statement again — which is the duplication the
    pointers were introduced to end."""
    readme = normalised(text()).lower()

    dangling = {
        f"{path.relative_to(_ROOT)}: {claim}"
        for path in sorted(_ROOT.glob("apps/**/*.py"))
        if "/tests/" not in path.as_posix()
        for claim in re.findall(r"\(README:\s*([^)]+)\)", " ".join(path.read_text().split()))
        if claim.strip().rstrip(".").lower() not in readme
    }

    assert dangling == set()
