from typing import Any, Protocol

import httpx


class ApiProtocol(Protocol):
    _response: httpx.Response | None
    _last_registered_email: str | None

    def _run(self, coro: Any) -> Any: ...

    def track_auth_email(self, email: str) -> None: ...

    def track_org_id(self, org_id: str) -> None: ...

    @property
    def _c(self) -> httpx.AsyncClient: ...

    def _client_for(self, email: str) -> httpx.AsyncClient: ...

    def _make_client_for(self, email: str) -> httpx.AsyncClient: ...

    def _user_id_for_email(self, email: str) -> str: ...

    def _restore_clock(self) -> None: ...

    def ensure_clock(self, default_iso: str) -> None: ...

    def demote_to_member(self) -> None: ...

    def delete_todo(self, title: str) -> None: ...

    def rename_todo(self, title: str, new_title: str) -> None: ...


class BrowserProtocol(Protocol):
    _base_url: str
    _last_response: Any
    _last_registered_email: str | None
    _context: Any
    _action_blocked_by_ui: bool
    _last_error_text: str | None

    @property
    def _p(self) -> Any: ...

    def ensure_clock(self, default_iso: str) -> None: ...

    def _restore_clock(self) -> None: ...

    def _arm_dialogs(self, page: Any) -> None: ...

    def _click_and_capture(self, page: Any, selector: str, method: str, path_token: str) -> Any: ...

    def sign_in(self, email: str, password: str) -> None: ...

    def delete_todo(self, title: str) -> None: ...

    def rename_todo(self, title: str, new_title: str) -> None: ...
