import uuid
from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, ConfigDict
from sqlalchemy import Computed, ForeignKey, String, UniqueConstraint
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column

from apps.shared.dto import Partial
from apps.shared.persistence.base import (
    Base,
    OrgScoped,
    Positioned,
    Timestamped,
    UUIDPk,
    Versioned,
)


class PageVisibility(StrEnum):
    """``draft`` and ``members``: members only; ``public``: anyone."""

    draft = "draft"
    members = "members"
    public = "public"


class Page(Base, UUIDPk, OrgScoped, Versioned, Timestamped):
    __tablename__ = "pages"
    __table_args__ = (UniqueConstraint("org_id", "slug"),)

    user_id: Mapped[uuid.UUID]
    title: Mapped[str] = mapped_column(String)
    slug: Mapped[str] = mapped_column(String)
    content: Mapped[str] = mapped_column(String, default="")
    visibility: Mapped[PageVisibility] = mapped_column(
        SAEnum(PageVisibility, name="page_visibility", create_type=False),
        default=PageVisibility.draft,
    )
    # Generated by the database. Never null: an empty page gives an empty tsvector.
    search_vector: Mapped[str] = mapped_column(
        TSVECTOR,
        Computed(
            "to_tsvector('english', coalesce(title, '') || ' ' || coalesce(content, ''))",
            persisted=True,
        ),
        nullable=False,
    )


class PageRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    title: str
    slug: str
    visibility: PageVisibility
    created_at: datetime


class PageDocumentRead(PageRead):
    """A page with its Markdown, the HTML the app rendered from it, and whether the reader may
    edit it."""

    content: str
    body_html: str
    can_edit: bool

    @classmethod
    def of(cls, page: Page, *, body_html: str, can_edit: bool) -> PageDocumentRead:
        return cls(
            **PageRead.model_validate(page).model_dump(),
            content=page.content,
            body_html=body_html,
            can_edit=can_edit,
        )


class PageNavItem(Base, UUIDPk, OrgScoped, Positioned, Versioned, Timestamped):
    __tablename__ = "page_nav_items"
    __table_args__ = (UniqueConstraint("org_id", "page_id"),)

    page_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("pages.id"))


class NavCandidate(BaseModel):
    """For the nav manager."""

    page_id: uuid.UUID
    slug: str
    title: str
    visibility: PageVisibility
    in_nav: bool
    position: int | None


class PageCreate(BaseModel):
    """A blank title is refused by the handler; a blank slug is derived."""

    title: str = ""
    content: str = ""
    slug: str = ""


class PagePatch(Partial):
    """The editor sends the whole form, a JSON caller what changed."""

    title: str = ""
    content: str = ""
    slug: str = ""
    visibility: PageVisibility = PageVisibility.draft


class PageVisibilityUpdate(BaseModel):
    visibility: PageVisibility


class NavAdd(BaseModel):
    slug: str = ""


class NavMove(BaseModel):
    """Above ``above_slug``, or last."""

    above_slug: str | None = None


class NavItemRead(BaseModel):
    page_id: uuid.UUID
    slug: str
    title: str
    visibility: PageVisibility


class PublicPage(BaseModel):
    page: PageRead
    nav: list[NavItemRead]
